apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: solr-operator
  namespace: flux-system
spec:
  releaseName: solr-operator
  targetNamespace: solr-operator
  storageNamespace: solr-operator
  chart:
    spec:
      chart: solr-operator
      sourceRef:
        kind: HelmRepository
        name: apache-solr
      version: 0.6.0
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    zookeeper-operator:
      install: false
